server:
  port: 8084

spring:
  application:
    name: "BusBuddy"
  data:
    mongodb:
      host: localhost
      uri: mongodb://admin:admin@BusBuddy-DB:27017/BusBuddy?authSource=admin

      port: 27017
      database: BusBuddy
      username: admin
      password: admin
      authentication-database: admin

    liquibase:
      enabled: true
      change-log: classpath:db/changelog/db.changelog-master.yml
      url: mongodb://admin:admin@BusBuddy-DB:27017/BusBuddy?authSource=admin
      user: admin
      password: admin
      default-schema: BusBuddy
      changeLogLockWaitTime: 600
  profiles:
    active: "prod"